name: "Incidència TIC"
description: "Registrar una incidència TIC"
title: "[INC] "

body:
  - type: markdown
    attributes:
      value: |
        Completa la informació de la incidència.

  - type: input
    id: usuari
    attributes:
      label: "Nom de l'usuari"
    validations:
      required: true

  - type: input
    id: ubicacio
    attributes:
      label: "Ubicació"

  - type: dropdown
    id: prioritat
    attributes:
      label: "Prioritat"
      options:
        - alta
        - mitjana
        - baixa
    validations:
      required: true

  - type: textarea
    id: incidencia
    attributes:
      label: "Descripció de la incidència"
    validations:
      required: true

  - type: textarea
    id: observacions
    attributes:
      label: "Observacions"